/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RPCServer;

import RPCServer.controller.XMLServer;
import org.apache.xmlrpc.server.PropertyHandlerMapping;
import org.apache.xmlrpc.server.XmlRpcServer;
import org.apache.xmlrpc.webserver.WebServer;
import org.restlet.Application;

public class App extends Application{
    public static void main(String[] args) throws Exception {

        System.out.println("XML-RPC Server Start!");

        WebServer webServer = new WebServer(8889);
        XmlRpcServer xmlRpcServer = webServer.getXmlRpcServer();
        PropertyHandlerMapping propertyHandlerMapping = new PropertyHandlerMapping();
        
        propertyHandlerMapping.addHandler("vmAction", XMLServer.class);
        xmlRpcServer.setHandlerMapping(propertyHandlerMapping);

        webServer.start();
    }
}
