/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RPCServer;

import org.restlet.data.Protocol;
import RPCServer.controller.VmRunActionController;
import RPCServer.controller.VmStopActionController;
import org.restlet.Application;
import org.restlet.Component;

public class App extends Application{
    public static void main(String[] args) throws Exception {
        Component component =  new Component();
        component.getServers().add(Protocol.HTTP, 8889);

        component.getDefaultHost().attach("/vmRunAction/{macAddress}", VmRunActionController.class);
        component.getDefaultHost().attach("/vmStopAction/{macAddress}", VmStopActionController.class);

        component.start();
    }
}
